services:
  - type: web
    name: sitedpcz
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 20
    staticPublishPath: dist
    autoDeploy: true
